apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: '4.0.18'
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  values:
    nfs:
      server: 192.168.1.10
      path: /mnt/k8s
    storageClass:
      defaultClass: true
      name: nfs-01
      provisionerName: nfs-provisioner-01
    replicaCount: 1
  interval: 10m
  timeout: 5m
  releaseName: nfs-subdir-external-provisioner
  # valuesFrom:
  # - kind: ConfigMap
  #   name: nfs-subdir-external-provisioner-helm-chart-value-overrides
  #   valuesKey: values.yaml # This is the default, but best to be explicit for clarity