apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '61.4.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: monitoring
  valuesFrom:
  - kind: ConfigMap
    name: monitoring-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity