apiVersion: v1
kind: ConfigMap
metadata:
  name: intel-device-plugin-helm-chart-value-overrides
  namespace: intel
data:
  values.yaml: |-
    nodeSelector:
      kubernetes.io/arch: amd64

    manager:
      image:
        hub: intel
        tag: ""
        pullPolicy: IfNotPresent

    kubeRbacProxy:
      image:
        hub: gcr.io
        hubRepo: kubebuilder
        tag: v0.16.0
        pullPolicy: IfNotPresent

    privateRegistry:
      registryUrl: ""
      registryUser: ""
      registrySecret: ""

    resources:
      limits:
        cpu: 100m
        memory: 120Mi
      requests:
        cpu: 100m
        memory: 100Mi
    nodeFeatureRule: true