apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugin
  namespace: intel
spec:
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: '0.30.0'
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  interval: 10m
  timeout: 5m
  releaseName: intel-device-plugin
  valuesFrom:
  - kind: ConfigMap
    name: intel-device-plugin-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity